name: Update PDF List

on:
  push:
    paths:
      - 'pdfs/**'

jobs:
  update-pdf-list:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get the list of PDF files in the 'pdfs' folder
      - name: Get PDF list
        run: |
          echo "Generating list of PDFs..."
          PDF_FILES=$(find pdfs -type f -name "*.pdf")
          echo "Found the following PDFs:"
          echo "$PDF_FILES"
          
          # Create a file with the PDF file paths for later use
          echo "$PDF_FILES" > pdf_list.txt

      # Update the script.js with the new PDF list
      - name: Update script.js
        run: |
          echo "Updating script.js with new PDF list..."
          echo "const pdfs = [" > script.js
          
          # URL encode spaces and special characters
          url_encode() {
            local string="$1"
            echo -n "$string" | jq -sRr @uri
          }

          # Loop through each PDF file and add it to the script.js file
          while IFS= read -r pdf; do
            title=$(basename "$pdf" .pdf)
            encoded_pdf=$(url_encode "$pdf")
            # Append the data in the required format
            echo "    { title: \"$title\", file: \"$encoded_pdf\" }," >> script.js
          done < pdf_list.txt
          echo "];" >> script.js

      # Commit and push the changes to script.js
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Use the token to authenticate and set the remote URL
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          
          git add script.js
          git commit -m "Auto-update script.js with new PDFs"
          git push
