name: Auto Update PDFs

on:
  push:
    branches:
      - main

jobs:
  update-pdf-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate list of PDFs
        run: |
          echo "Generating list of PDFs..."
          PDFs=$(find ./pdfs -type f -name "*.pdf")
          echo "Found the following PDFs:"
          echo "$PDFs"
          
          # Generate the list in script.js (you can modify this as per your actual needs)
          echo "Updating script.js with new PDFs"
          echo "const pdfs = [" > script.js
          for file in $PDFs; do
            # Format the file path and title
            title=$(basename "$file" | sed 's/%20/ /g')  # Replace %20 with space
            file_path="\"$file\""
            echo "    { title: \"$title\", file: $file_path }," >> script.js
          done
          echo "];" >> script.js

      - name: Commit updated script.js
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add script.js
          git commit -m "Auto-update script.js with new PDFs"

      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/shahidinf9404/my-web-interface.git
          git push
