name: Update PDF List

on:
  push:
    paths:
      - 'pdfs/**'

jobs:
  update-pdf-list:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get the list of PDF files in the 'pdfs' folder
      - name: Get PDF list
        run: |
          echo "Generating list of PDFs..."
          PDF_FILES=$(ls pdfs/*.pdf)
          echo "Found the following PDFs: $PDF_FILES"
          echo "PDF_FILES=$PDF_FILES" >> $GITHUB_ENV

      # Update the script.js with the new PDF list
      - name: Update script.js
        run: |
          echo "Updating script.js with new PDF list..."
          echo "const pdfs = [" > script.js
          for pdf in $PDF_FILES; do
            title=$(basename "$pdf" .pdf)
            echo "    { title: \"$title\", file: \"$pdf\" }," >> script.js
          done
          echo "];" >> script.js

      # Commit and push the changes to script.js
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git add script.js
          git commit -m "Auto-update script.js with new PDFs"
          git push
