name: Update PDF List

on:
  push:
    paths:
      - 'pdfs/**'  # Trigger when PDF files in the 'pdfs' folder are changed

jobs:
  update-pdf-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update script.js with new PDFs
      run: |
        # Find all PDF files in the pdfs directory
        PDF_FILES=$(find pdfs -name "*.pdf" -type f)

        # Start building the PDF list array in script.js
        echo "const pdfs = [" > script.js

        # Loop through the PDF files and add them to script.js
        for file in $PDF_FILES; do
          # Extract the PDF filename without the path
          FILENAME=$(basename "$file")
          TITLE=$(echo "$FILENAME" | sed 's/%20/ /g')  # Decode %20 to space
          echo "    { title: \"$TITLE\", file: \"$file\" }," >> script.js
        done

        # End the PDF list array
        echo "];" >> script.js

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add script.js
        git commit -m "Auto-update script.js with new PDFs"
        git push origin main
